# Generated by Django 4.1 on 2022-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=200, null=True)),
                ('OriginCountry', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'MobileBrands',
            },
        ),
    ]
