# Generated by Django 4.1 on 2022-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.IntegerField()),
                ('ORDERDATE', models.DateField()),
                ('SHIIPPINGDATE', models.DateField()),
                ('PRODUCTID', models.IntegerField()),
                ('QUANTITY', models.IntegerField()),
                ('COST', models.IntegerField()),
                ('Discount', models.FloatField()),
                ('TotalAmountBeforeTax', models.IntegerField()),
                ('OrdTotal', models.IntegerField()),
                ('PaymentMethod', models.CharField(max_length=100)),
                ('CustomerID', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
            ],options={
                'db_table': 'orderdetails',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=200, null=True)),
                ('OriginCountry', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'MobileBrands',
            },
        ),
    ]
